# Generated by Django 2.1 on 2018-08-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180824_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Aimg',
            field=models.ImageField(default='/static/background/pic01.jpg', upload_to='background'),
        ),
    ]
